version: "3.9"
services:
  # database container
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - /var/lib/mongodb:/data/db

  # api container
  api:
    build:
      dockerfile: ./Dockerfile
    ports:
      - 4000:8000
    environment:
      PORT: 8000
      DB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
    depends_on:
      - mongo_db

volumes: {}
